# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  checkout: self
  submodules: true
  task: AzureStaticWebApp@0
    inputs:
      app_location: "./" # App source code path
      api_location: "" # Api source code path 
      output_location: "_site" # Built app content directory
      azure_static_web_apps_api_token: $(deployment-token)

# - task: UseRubyVersion@0
#   inputs:
#     versionSpec: '>= 2.5'

# - task: UseNode@1
#   inputs:
#     version: '20.x'

# - script: |
#     gem install jekyll bundler
#     bundle install --retry=3 --jobs=4
#   displayName: 'bundle install'

# - script: |
#     bundle install
#     npm run build
#     jekyll build
#   displayName: 'jekyll'

# - task: CopyFiles@2
#   displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
#   inputs:
#     SourceFolder: '_site'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     artifactName: site
